### ISSUE TITLE
MAX110606

### ISSUE THREAD

**Issue by ghost** [AllAboutEE/MAX11609EEE-Breakout-Board#1]
Would it be possible for you to modify this library to enable use of the MAX11606?

Voltage levels need to be adjusted and the amount of pins. The adjustments are relatively small.

**Comment by AllAboutEE** [comment]
I don't have a MAX11606, if I did I would. Closing because: This is not an issue but a request.

**Comment by Tensa225** [comment]
Can you adjust the code and let me do the testing?

Ot I can send you several of these chips (depending on your location). I would appreciate it highly.
